import JamRecurrentMaintenance
import Mathlib.Analysis.SpecificLimits.Basic

namespace DistributedCommons

/-!
# JAM: dynamic corrective resilience

`JamRecurrentMaintenance.lean` separates within-audit corrective reproduction
from cross-audit maintenance viability. This module couples the two timescales.

The slow state has three coordinates:

* `corrective` -- the normalized, fault-specific independently-correct share
  that feeds the next audit's corrective reproduction number;
* `observability` -- capacity to observe or attribute genuine maintenance;
* `resources` -- resources returned to preserve future corrective capacity.

The declared linear update is

  C' = rC C + kRC R
  O' = rO O + kCO C
  R' = rR R + kOR O.

For a fixed audit escalation factor `F`, the next audit's fast reproduction
number is `F * C`. The main exact bridge proved here is therefore local and
measurable: at the fast critical boundary `F*C = 1`, the next audit remains at
or above criticality exactly when returned resources close the current
corrective-capacity replacement gap.

A reduced one-parameter path is also used to prove an identification result:
the same current reproduction number can imply different finite-horizon
resilience depending on the cross-audit maintenance multiplier. This is a
model theorem, not a claim that JAM currently has any particular slow-state
coefficients or multiplier.
-/

/-- Slow state supporting future independently-correct auditing. `corrective`
is normalized to the validator population relevant to the fast audit model. -/
structure JamCorrectiveState where
  corrective : ℝ
  observability : ℝ
  resources : ℝ

/-- One cross-audit update of corrective capacity, maintenance observability,
and returned resources. -/
def jamCorrectiveStateStep
    (rC rO rR kCO kOR kRC : ℝ)
    (x : JamCorrectiveState) : JamCorrectiveState :=
  { corrective := rC * x.corrective + kRC * x.resources
    observability := rO * x.observability + kCO * x.corrective
    resources := rR * x.resources + kOR * x.observability }

/-- Fast, fault-specific audit reproduction generated by the current slow
corrective-capacity coordinate. -/
noncomputable def jamStateCorrectionReproduction
    (F : ℝ) (x : JamCorrectiveState) : ℝ :=
  F * x.corrective

/-- Fast supercriticality of the current state. -/
def jamStateCorrectionSupercritical
    (F : ℝ) (x : JamCorrectiveState) : Prop :=
  1 < jamStateCorrectionReproduction F x

/-- Exact bridge from the slow state update to the next audit reproduction
number. The observability and resource equations matter for later rounds, but
the immediate next-audit bridge enters through the returned-resource term in
`C'`. -/
theorem jam_next_reproduction_identity
    (F rC rO rR kCO kOR kRC : ℝ)
    (x : JamCorrectiveState) :
    jamStateCorrectionReproduction F
        (jamCorrectiveStateStep rC rO rR kCO kOR kRC x)
      =
    rC * jamStateCorrectionReproduction F x
      + F * kRC * x.resources := by
  unfold jamStateCorrectionReproduction jamCorrectiveStateStep
  ring

/-- **Maintenance-return boundary.** If the current fast audit is exactly at
criticality, then the next audit stays at or above criticality iff returned
resources close the autonomous loss of corrective capacity.

The right-hand side is intentionally written without division, so it remains
meaningful even when `F` or `kRC` is zero. -/
theorem jam_critical_return_boundary
    {F rC rO rR kCO kOR kRC : ℝ}
    {x : JamCorrectiveState}
    (hcrit : jamStateCorrectionReproduction F x = 1) :
    1 ≤ jamStateCorrectionReproduction F
        (jamCorrectiveStateStep rC rO rR kCO kOR kRC x)
      ↔
    1 - rC ≤ F * kRC * x.resources := by
  rw [jam_next_reproduction_identity, hcrit]
  constructor <;> intro h <;> nlinarith

/-- At current criticality, a strict shortfall in the returned-resource term
forces the next audit below the fast correction threshold. -/
theorem jam_return_shortfall_makes_next_audit_subcritical
    {F rC rO rR kCO kOR kRC : ℝ}
    {x : JamCorrectiveState}
    (hcrit : jamStateCorrectionReproduction F x = 1)
    (hshort : F * kRC * x.resources < 1 - rC) :
    jamStateCorrectionReproduction F
        (jamCorrectiveStateStep rC rO rR kCO kOR kRC x) < 1 := by
  rw [jam_next_reproduction_identity, hcrit]
  nlinarith

/-- Conversely, a strict returned-resource surplus above the replacement gap
makes the next audit supercritical when the current audit is exactly critical. -/
theorem jam_return_surplus_makes_next_audit_supercritical
    {F rC rO rR kCO kOR kRC : ℝ}
    {x : JamCorrectiveState}
    (hcrit : jamStateCorrectionReproduction F x = 1)
    (hsurplus : 1 - rC < F * kRC * x.resources) :
    1 < jamStateCorrectionReproduction F
        (jamCorrectiveStateStep rC rO rR kCO kOR kRC x) := by
  rw [jam_next_reproduction_identity, hcrit]
  nlinarith

/-- Reduced cross-audit trajectory for the fast correction reproduction number.
`m` is a net maintenance multiplier for this reduced coordinate; it is not the
same object as the three-process loop ratio from `JamRecurrentMaintenance`. -/
noncomputable def jamReducedCorrectionPath
    (lambda0 m : ℝ) (n : ℕ) : ℝ :=
  m ^ n * lambda0

/-- The reduced path starts at the observed current reproduction number. -/
theorem jamReducedCorrectionPath_zero
    (lambda0 m : ℝ) :
    jamReducedCorrectionPath lambda0 m 0 = lambda0 := by
  simp [jamReducedCorrectionPath]

/-- Exact one-step recurrence of the reduced cross-audit path. -/
theorem jamReducedCorrectionPath_succ
    (lambda0 m : ℝ) (n : ℕ) :
    jamReducedCorrectionPath lambda0 m (n + 1)
      = m * jamReducedCorrectionPath lambda0 m n := by
  simp [jamReducedCorrectionPath, pow_succ]
  ring

/-- Margin above the fast ELVES-style critical boundary. -/
noncomputable def jamCorrectionMargin (lambda : ℝ) : ℝ :=
  lambda - 1

/-- Exact margin recursion. Because the fast threshold remains fixed at one,
a maintenance multiplier below one creates both multiplicative shrinkage of
existing margin and an additive replacement drag. -/
theorem jamCorrectionMargin_step
    (lambda m : ℝ) :
    jamCorrectionMargin (m * lambda)
      = m * jamCorrectionMargin lambda - (1 - m) := by
  unfold jamCorrectionMargin
  ring

/-- Any positive reproduction number strictly declines in one reduced step
when the maintenance multiplier lies below one. -/
theorem jamReducedCorrection_strictly_declines
    {lambda m : ℝ}
    (hlambda : 0 < lambda)
    (hm : m < 1) :
    m * lambda < lambda := by
  have hgap : 0 < (1 - m) * lambda :=
    mul_pos (sub_pos.mpr hm) hlambda
  nlinarith

/-- A nonnegative subunit reduced maintenance multiplier drives every finite
initial reproduction number to zero, hence eventually below the fast critical
threshold. This is the general reduced-model erosion theorem behind the finite
counterexample below. -/
theorem jamReducedCorrection_eventually_subcritical
    {lambda0 m : ℝ}
    (hm0 : 0 ≤ m)
    (hm1 : m < 1) :
    ∀ᶠ n : ℕ in Filter.atTop,
      jamReducedCorrectionPath lambda0 m n < 1 := by
  have hpow :
      Filter.Tendsto (fun n : ℕ => m ^ n) Filter.atTop (nhds 0) :=
    tendsto_pow_atTop_nhds_zero_of_lt_one hm0 hm1
  have hpath :
      Filter.Tendsto
        (fun n : ℕ => jamReducedCorrectionPath lambda0 m n)
        Filter.atTop (nhds 0) := by
    simpa [jamReducedCorrectionPath] using hpow.mul_const lambda0
  exact (tendsto_order.1 hpath).2 1 (by norm_num)

/-- In particular, some finite cross-audit horizon lies below criticality for
any nonnegative reduced multiplier strictly below one. -/
theorem jamReducedCorrection_eventually_crosses_threshold
    {lambda0 m : ℝ}
    (hm0 : 0 ≤ m)
    (hm1 : m < 1) :
    ∃ n : ℕ, jamReducedCorrectionPath lambda0 m n < 1 := by
  exact (jamReducedCorrection_eventually_subcritical hm0 hm1).exists

/-- Finite-horizon resilience in the reduced path. -/
def jamHorizonSupercritical
    (lambda0 m : ℝ) (T : ℕ) : Prop :=
  1 < jamReducedCorrectionPath lambda0 m T

/-- **Current audit success is not a sufficient statistic for horizon
resilience.** Two systems can have exactly the same current supercritical
reproduction number and different five-step status solely because their
cross-audit maintenance multipliers differ.

The numbers are a transparent counterexample, not calibrated JAM estimates:
`lambda0 = 3/2`; perfect replacement keeps it at `3/2`, while multiplier
`9/10` yields `(9/10)^5 * (3/2) < 1`. -/
theorem event_level_success_not_sufficient_statistic_for_five_step_resilience :
    ∃ lambda0 mStable mErode : ℝ,
      1 < lambda0 ∧
      jamReducedCorrectionPath lambda0 mStable 0 =
        jamReducedCorrectionPath lambda0 mErode 0 ∧
      jamHorizonSupercritical lambda0 mStable 5 ∧
      ¬ jamHorizonSupercritical lambda0 mErode 5 := by
  refine ⟨3 / 2, 1, 9 / 10, ?_⟩
  norm_num [jamReducedCorrectionPath, jamHorizonSupercritical]

/-- Concrete full-state witness of latent loss: current correction is
supercritical, but with no returned-resource contribution and only half of the
corrective coordinate retained, the next audit becomes subcritical. -/
theorem current_supercritical_can_cross_subcritical_next_round :
    let x : JamCorrectiveState :=
      { corrective := 3 / 4, observability := 1, resources := 1 }
    jamStateCorrectionSupercritical 2 x ∧
    ¬ jamStateCorrectionSupercritical 2
      (jamCorrectiveStateStep (1 / 2) 1 1 1 1 0 x) := by
  norm_num [jamStateCorrectionSupercritical, jamStateCorrectionReproduction,
    jamCorrectiveStateStep]

#print axioms jam_next_reproduction_identity
#print axioms jam_critical_return_boundary
#print axioms jam_return_shortfall_makes_next_audit_subcritical
#print axioms jam_return_surplus_makes_next_audit_supercritical
#print axioms jamReducedCorrectionPath_succ
#print axioms jamCorrectionMargin_step
#print axioms jamReducedCorrection_strictly_declines
#print axioms jamReducedCorrection_eventually_subcritical
#print axioms jamReducedCorrection_eventually_crosses_threshold
#print axioms event_level_success_not_sufficient_statistic_for_five_step_resilience
#print axioms current_supercritical_can_cross_subcritical_next_round

end DistributedCommons
