"""Models for distributed maintenance of shared state."""

from .model import (
    ControlPhase,
    DynamicsParameters,
    EffortRequirement,
    PhaseAssessment,
    RoundRecord,
    assess_control_phase,
    bad_finalization_probability,
    conditional_detection_probability,
    conditional_escape_probability,
    endogenous_bad_finalization_floor,
    monitor_objective,
    producer_bad_attempt_floor,
    producer_floor_envelope,
    producer_target_bad_rate,
    selected_control_is_sufficient,
    selected_effort,
    simulate,
    sufficient_effort,
)

__all__ = [
    "ControlPhase",
    "DynamicsParameters",
    "EffortRequirement",
    "PhaseAssessment",
    "RoundRecord",
    "assess_control_phase",
    "bad_finalization_probability",
    "conditional_detection_probability",
    "conditional_escape_probability",
    "endogenous_bad_finalization_floor",
    "monitor_objective",
    "producer_bad_attempt_floor",
    "producer_floor_envelope",
    "producer_target_bad_rate",
    "selected_control_is_sufficient",
    "selected_effort",
    "simulate",
    "sufficient_effort",
    "BehaviouralEquilibrium",
    "ClosedLoopParameters",
    "ClosedLoopRecord",
    "HysteresisWindow",
    "basin_threshold",
    "behavioural_equilibrium",
    "bifurcation_curve",
    "critical_baseline_funding",
    "equilibrium_damage",
    "final_health",
    "hysteresis_window",
    "loop_gain",
    "simulate_closed_loop",
    "FailureCause",
    "FailureTopology",
    "Participant",
    "two_cause_example",
    "attack_success_bound",
    "critical_client_bug_share",
    "economic_soundness_threshold",
    "expected_committee_bound",
    "honest_reproduction",
    "max_client_bug_share_for_target",
    "required_collateral_share",
    "REVERSAL_THRESHOLD",
    "critical_cost_ratio",
    "direct_addition_contribution",
    "induced_response_effect",
    "one_selected_margin",
    "selected_addition_contribution",
    "two_frozen_margin",
    "two_participant_effort",
    "two_selected_margin",
    "CapacityParameters",
    "local_shared_state_multiplier",
    "maintenance_shortfall",
    "post_shock_state",
    "quiet_step",
    "quiet_trajectory",
    "required_maintenance_for_capacity",
    "shock_is_viable",
    "shock_margin",
    "uncapped_shock_margin",
    "certified_access_margin",
    "certified_participant_contribution",
    "expected_access_margin",
    "expected_participant_contribution",
    "ContributionVector",
    "opposite_sign_weight_witnesses",
    "MaintenanceParameters",
    "boundary_is_preserved",
    "correction_is_locally_stable",
    "correction_multiplier",
    "decentralized_boundary_is_preserved",
    "effective_corrective_gain",
    "noisy_correction_multiplier",
    "overcorrection_threshold",
    "passive_renewal_suffices",
    "positive_reinforcement_is_beneficial",
    "reinforcement_value_numerator",
    "repair_is_worthwhile",
    "repair_net_value",
    "replacement_gap",
    "target_baseline_maintenance",
    "JamMaintenanceState",
    "escalation_vector_change",
    "one_validator_correction_gain",
    "one_validator_scalability_gain",
    "AuditBehaviorPayoffs",
    "certified_exposure_lower_bound",
    "certified_required_reward_advantage_over_rubber",
    "required_compute_reward_advantage_over_no_show",
    "required_compute_reward_advantage_over_rubber",
    "rubber_stamp_beats_no_show",
]

from .closed_loop import (
    BehaviouralEquilibrium,
    ClosedLoopParameters,
    ClosedLoopRecord,
    HysteresisWindow,
    basin_threshold,
    behavioural_equilibrium,
    bifurcation_curve,
    critical_baseline_funding,
    equilibrium_damage,
    final_health,
    hysteresis_window,
    loop_gain,
    simulate_closed_loop,
)

from .viability import (
    FailureCause,
    FailureTopology,
    Participant,
    two_cause_example,
)

from .jam_elves import (
    attack_success_bound,
    critical_client_bug_share,
    economic_soundness_threshold,
    expected_committee_bound,
    honest_reproduction,
    max_client_bug_share_for_target,
    required_collateral_share,
)

from .selected_viability import (
    REVERSAL_THRESHOLD,
    critical_cost_ratio,
    direct_addition_contribution,
    induced_response_effect,
    one_selected_margin,
    selected_addition_contribution,
    two_frozen_margin,
    two_participant_effort,
    two_selected_margin,
)

from .corrective_capacity import (
    CapacityParameters,
    local_shared_state_multiplier,
    maintenance_shortfall,
    post_shock_state,
    quiet_step,
    quiet_trajectory,
    required_maintenance_for_capacity,
    shock_is_viable,
    shock_margin,
    uncapped_shock_margin,
)

from .state_dependent_contribution import (
    certified_access_margin,
    certified_participant_contribution,
    expected_access_margin,
    expected_participant_contribution,
)

from .vector_contribution import (
    ContributionVector,
    opposite_sign_weight_witnesses,
)

from .behavioral_maintenance import (
    MaintenanceParameters,
    boundary_is_preserved,
    correction_is_locally_stable,
    correction_multiplier,
    decentralized_boundary_is_preserved,
    effective_corrective_gain,
    noisy_correction_multiplier,
    overcorrection_threshold,
    passive_renewal_suffices,
    positive_reinforcement_is_beneficial,
    reinforcement_value_numerator,
    repair_is_worthwhile,
    repair_net_value,
    replacement_gap,
    target_baseline_maintenance,
)

from .jam_maintenance import (
    JamMaintenanceState,
    escalation_vector_change,
    one_validator_correction_gain,
    one_validator_scalability_gain,
)

from .jam_behavior_selection import (
    AuditBehaviorPayoffs,
    certified_exposure_lower_bound,
    certified_required_reward_advantage_over_rubber,
    required_compute_reward_advantage_over_no_show,
    required_compute_reward_advantage_over_rubber,
    rubber_stamp_beats_no_show,
)
